### ISSUE TITLE
Login is broken on Firefox. 

### ISSUE THREAD

**Issue by xusiai** [linkwarden/browser-extension#17]
I cannot log in via the Firefox extension. I have reproduced this with a clean profile and both return: `something went wrong, try again later`. Linkwarden instance is selfhosted and accessible over localhost with the Chromium extension.

**Comment by crkos** [comment]
Yes this is a problem with specifically firefox we know about
![SolutionError](https://github.com/linkwarden/browser-extension/assets/92697104/ffd167c0-4936-4765-8202-d309e80c94ca)

You can currently resolve this by enabling this option that i put above, It is likely that this is due to permissions in the manifest which is something doesn't happen on chrome, I may have to specify required permissions on the manifest on the firefox side.

**Comment by crkos** [comment]
You may encounter other bugs related to firefox you are free to open other issues as they are being actively worked on

**Comment by xusiai** [comment]
> You can currently resolve this by enabling this option that i put above, It is likely that this is due to permissions in the manifest which is something doesn't happen on chrome, I may have to specify required permissions on the manifest on the firefox side.

Unfortunately enabling these preferences do not resolve the issue for me.

**Comment by crkos** [comment]
Can you tell me which version of linkwarden are you using?

**Comment by xusiai** [comment]
> If you are using anything below 1.0.1 I think it wont work, because the api routes for that version were updated

I don't see a version listed in Linkwarden however as I set it up via Docker 9 hours ago (from the official Linkwarden repo) and as nothing seems to have been released since I would assume I am running the latest version.

**Comment by xusiai** [comment]
![swappy-20230918_185301](https://github.com/linkwarden/browser-extension/assets/142084577/83e4675d-7339-48a8-9e69-1193f2de19e0)

**Comment by crkos** [comment]
Mmm, I previously had this issue, but it was resolved, I think it had to do with https, maybe i haven't updated the extension i will check

**Comment by xusiai** [comment]
> Mmm, I previously had this issue, but it was resolved, I think it had to do with https, maybe i haven't updated the extension i will check

My extension version is 1.0.1 installed via the Mozilla addon store.

**Comment by crkos** [comment]
It's weird because i have reinstalled in both version of firefox and firefox dev, and both work fine, with a local hosted enviroment, are you using self signed certs for https or anything of that sort?

**Comment by crkos** [comment]
Yes mine is also 117.0

**Comment by crkos** [comment]
Ok i managed to reproduce it, I think it has to with self hosting on local network, I'm gonna work on this, Maybe it will be done by today, sorry for the incoveniences, As i didn't tested this, It was working on localhost, so i just assumed would work over the network, on chrome this doesn't happen for some reason it only happens on firefox

**Comment by crkos** [comment]
I know what's the problem, It's the CSP which in firefox is triying to upgrade every http request, I would advise to try to self-sign and do https, just for the time being, This is not hard and can be done in a few minutes, This should resolve that for the time being, This fix is only for users of firefox, users using any chromium based browsers shouldn't be affected.

I searched but could'nt find anywhere of how i could force to do http, i tried CSP policies to no avail on headers in request and html meta tags, It seems that firefox is very strict when it comes to request from the network

**Comment by crkos** [comment]
So your problem is not that the linkwarden is not working, Is that firefox is triying to use HTTPS but it's doesn't find a working Cert it just fails to do the request, if you want to use it, I would advise to use a chromium browser, or to add https to your instance, Meanwhile i can search for a fix, maybe on webworkers can find a solution.

**Comment by crkos** [comment]
Ok, I managed to fix it, It was the V3 manifest, So i had to do a V2 for firefox and use V3 on chrome, so yeah it will be like that, V2 it's better for firefox, At this point i uploaded the new revision to the mozilla extension, just wait a little bit until it's cleared up and updated then reinstall and let me know if it's fixed so i can close this issue!

**Comment by SoCuul** [comment]
> Ok, I managed to fix it, It was the V3 manifest, So i had to do a V2 for firefox and use V3 on chrome, so yeah it will be like that, V2 it's better for firefox, At this point i uploaded the new revision to the mozilla extension, just wait a little bit until it's cleared up and updated then reinstall and let me know if it's fixed so i can close this issue!

Hey! Do you have an eta on when it'll be live on the mozilla store? No rush haha, love what you're doing with this extension :)

**Comment by crkos** [comment]
I really can't give you an ETA since mozzilla is doing revision because i added a privacy notice late, Probably by tomorrow should be up, Typically doesn't take much time, by the time being if you can use the chrome one, it's usable, if you don't wanna wait, you can download the firefox branch add it yourself, just follow the same instructions, but now just zip the files inside dist and you should good to go

**Comment by SoCuul** [comment]
> I really can't give you an ETA since mozzilla is doing revision because i added a privacy notice late, Probably by tomorrow should be up, Typically doesn't take much time, by the time being if you can use the chrome one, it's usable, if you don't wanna wait, you can download the firefox branch add it yourself, just follow the same instructions, but now just zip the files inside dist and you should good to go

Thanks, man!

**Comment by SoCuul** [comment]
> I really can't give you an ETA since mozzilla is doing revision because i added a privacy notice late, Probably by tomorrow should be up, Typically doesn't take much time, by the time being if you can use the chrome one, it's usable, if you don't wanna wait, you can download the firefox branch add it yourself, just follow the same instructions, but now just zip the files inside dist and you should good to go

I signed the extension with my own developer account, installed it and it works perfectly! Thanks for your help :D

**Comment by SoCuul** [comment]
> I really can't give you an ETA since mozzilla is doing revision because i added a privacy notice late, Probably by tomorrow should be up, Typically doesn't take much time, by the time being if you can use the chrome one, it's usable, if you don't wanna wait, you can download the firefox branch add it yourself, just follow the same instructions, but now just zip the files inside dist and you should good to go

Ooh i have one singular problem. When I try to save a link, it works fine other than the fact that it won't let me show the dropdown list to select which collection I want to save it in. It highlights around it, but no dropdown appears. Though, the links do save under the default "Unorganized" collection just fine.

<img width="384" alt="image" src="https://github.com/linkwarden/browser-extension/assets/63339559/02a3b32a-2ad9-4240-9ad8-baab66072554">

**Comment by crkos** [comment]
I do know about this problem, though i havent had time to fix this, for some reason in firefox this doesn't work, in chrome works just fine, i suspect is just compatibility issues with the components, which i doubt, I will probably have this fix by today, in the meantime as you say you can save them as the default collection

**Comment by crkos** [comment]
Extension is now updated on the mozilla extension store

**Comment by xusiai** [comment]
For people who are still experiencing this issue (which I was) make sure you add an exception for Linkwarden's ip to Firefox's https-only mode if you have it enabled. I have not had to do this for other containers on localhost but doing so resolved this issue for Linkwarden.

**Comment by esmoyer** [comment]
Just updated today and am getting this error. Was working well prior and tried the above; anyone else have this issue return?

**Comment by crkos** [comment]
This is most likely because theres is a new version of linkwarden and the extension changed the api routes to comply with the new version, try update linkwarden to the newest version

**Comment by esmoyer** [comment]
Thanks for the quick reply. I did upgrade following the instructions. I even just wiped everything and started fresh but still get the error. In the firefox debug I am getting a 404, so might be something else on my end; just not sure what yet....

**Comment by crkos** [comment]
Can you send an ss of the error in the debug, I built last version yesterday and shipped same day on firefox, because i just checked so i doubt i update an old version

**Comment by esmoyer** [comment]
You bet...let me know if this doesn't work...
![image](https://github.com/linkwarden/browser-extension/assets/17444085/0e46f67a-846c-4144-844e-7cb26aeb081f)

**Comment by crkos** [comment]
I just installed everything clean, I wasn't able to reproduce it, Can you check if you have the latest version of the extension currently it is at 1.2.1

**Comment by esmoyer** [comment]
Indeed I do...maybe I am missing some Firefox setting, since it's working in Brave? I don't have the enforce HTTPS enabled but still added exceptions for my URL and the local IP...do I need to add an exception for my public IP? 

![image](https://github.com/linkwarden/browser-extension/assets/17444085/149166b2-52be-4eca-935f-34d2113ae350)

**Comment by crkos** [comment]
Can you check the permissions tab?
So i can see if you dont have the permissions

**Comment by esmoyer** [comment]
![image](https://github.com/linkwarden/browser-extension/assets/17444085/420d3dbd-d447-4e07-afc5-6050bb95eb1d)

**Comment by daniel31x13** [comment]
@esmoyer are you sure you are up to date with the latest linkwarden version? Looks like the `/api/v1/auth/csrf` route doesn't exist.

**Comment by esmoyer** [comment]
> @esmoyer are you sure you are up to date with the latest linkwarden version? Looks like the `/api/v1/auth/csrf` route doesn't exist.

Hmmm...I did do a fresh install tonight (deleted all folders, etc.) and it's pulling :main. Is there a way to check the version in the UI or somewhere to be sure?

**Comment by daniel31x13** [comment]
Do you see "Recently Added Links" in your dashboard?

**Comment by xusiai** [comment]
> Hmmm...I did do a fresh install tonight (deleted all folders, etc.) and it's pulling :main. Is there a way to check the version in the UI or somewhere to be sure?

If you're running it in Docker make sure you've updated the docker image itself (or remove it before installing it so docker pulls the latest image). Fwiw it broke for me on the latest update as well but updating the Linkwarden docker image resolved it.

**Comment by esmoyer** [comment]
> Do you see "Recently Added Links" in your dashboard?

Not that I can tell...so I assume I'm not on latest? 

Thanks @xusiai, I did indeed remove both the app and DB images prior to redeploying. Maybe I have the wrong tag? Is `main` not correct?

**Comment by daniel31x13** [comment]
@esmoyer yep, and I need to include the version tag somewhere in the app (perhaps in the login page?) instead of asking "do you see X..."

**Comment by esmoyer** [comment]
Aha! Changed to `latest` and it's going now! Go figure it was something stupid on my end. Appreciate the assist; hopefully this will help any others who come across it! Thanks so much!
