### ISSUE TITLE
Not possible to select collection on Firefox

### ISSUE THREAD

**Issue by SoCuul** [linkwarden/browser-extension#22]
When I try to save a link, it works fine other than the fact that it won't let me show the dropdown list to select which collection I want to save it in. It highlights around it, but no dropdown appears. Though, the links do save under the default "Unorganized" collection just fine.

![](https://user-images.githubusercontent.com/63339559/269538607-02a3b32a-2ad9-4240-9ad8-baab66072554.png)

**Comment by crkos** [comment]
Hello, thanks for the opening, I'm aware of this problem, Haven't had time to actually look into it very much, It only affects firefox afaik, I will be working on fixing it these days that i'm free

**Comment by crkos** [comment]
Hello, I just made a commit that should fix all the issues regarding this, please test the firefox branch and let me know if it's fixed for you so i can close this issue and begin the updating on the firefox store

**Comment by SoCuul** [comment]
> Hello, I just made a commit that should fix all the issues regarding this, please test the firefox branch and let me know if it's fixed for you so i can close this issue and begin the updating on the firefox store

I'll check it out later today! I also noticed that the drop-down worked fine if I accessed the extension page (the long extension:// page), even though it didn't work when I clicked on the icon in the toolbar.

**Comment by crkos** [comment]
Well it must be some kind of constraint on height or something like that, But i think the current one fits better to search the wanted collections instead of just scrolling.

**Comment by crkos** [comment]
but it is weird that nothing rendered, since on chrome all the behaviour is normal, I would think is one of those oddities between browsers, which is to be expected i guess, but makes some things harder to mantain

**Comment by SoCuul** [comment]
Eyyy, it works perfectly! Thanks man!

**Comment by crkos** [comment]
Thanks, closing issue
