### ISSUE TITLE
Endpoint URL

### ISSUE THREAD

**Issue by esmoyer** [linkwarden/browser-extension#28]
Hi, is there a specific endpoint this extension reaches out to aside form https://example.mydomain.com? Like is it /api/v2/..... or something like that? I am wanting to try and restrict firewall traffic. Thanks!

**Comment by crkos** [comment]
also these ones:
${url}/api/auth/csrf
${url}/api/auth/session

**Comment by crkos** [comment]
also these ones:
${url}/api/auth/csrf
${url}/api/auth/session

**Comment by esmoyer** [comment]
Excellent...thank you!
