### ISSUE TITLE
Linkwarden extension not communicating with Linkwarden's server

### ISSUE THREAD

**Issue by craigccfl** [linkwarden/browser-extension#33]
OS  Linux
Browsers Brave & other Chrome browsers, multiple computers. 

Error, "Something went wrong"  

Had it running for a few weeks, seamless. Now, when trying to use the extension, it's not connecting.  No problems connecting using a browser, both LAN and WAN, which rules out DNS issues. 

It's possible Brave and Chrome are blocking, if there's a security setting, it's something I don't know about.

**Comment by craigccfl** [comment]
Chrome Web Extension Store is version 1.2.0 dated Nov 9th as of Nov 15th. I deleted and reinstalled. Same result. It's not a deal breaker; however, the Linkwarden Web App is very convenient.

**Comment by crkos** [comment]
i didnt refer to the linkwarden extension, are you perhaps using docker?, if so then try to update the image, otherwise it will give errors, this has happened before, or when did it start to give problems if there are still problems

**Comment by craigccfl** [comment]
crkos: git pull and Docker update did the trick, working properly. BTW, liking the ascetic changes and will probably enjoy some of the back-end changes too. Thanks  👍
