### ISSUE TITLE
Unable to configure extension

### ISSUE THREAD

**Issue by craigtrevor** [linkwarden/browser-extension#44]
Attempted with both Firefox and Chrome extensions, I am logged into my Linkwarden instance on the same browser.

Fill out the URL / Username / Password fields, when clicking save, I get an 'Error Something went wrong, please try again'

**Comment by crkos** [comment]
Can you enter the debug mode on the extension on firefox or chrome and send a screenshot of it?, That would help me see what could be wrong

**Comment by craigtrevor** [comment]
![linkwarden exension network](https://github.com/linkwarden/browser-extension/assets/5953030/374a441a-78b6-4c06-97cf-be45eefa132f)

Appears to be getting 404 errors from my instance

**Comment by crkos** [comment]
Ok I will check it on my instance if i can reproduce it

**Comment by crkos** [comment]
Mmm can you tell me which version of linkwarden are you running, the most likely thing is that you ran into the same problem as some others like #17 

New version of linkwarden has update api routes so we updated the routes in the extension as well to make it work, if you you dont or cant update, then you can use an older version of the extension, I wouldn't reccommend that but if you want there is that option

**Comment by craigtrevor** [comment]
I am updating my docker container now.

**Comment by crkos** [comment]
Do you see the Recently Added Links on the dashboard?

**Comment by craigtrevor** [comment]
Nope.

**Comment by crkos** [comment]
Then the problem is your instance, make sure you are using the latest version, 2.3.0

**Comment by crkos** [comment]
instead of main you can do docker pull ghcr.io/linkwarden/linkwarden:latest or the version docker pull ghcr.io/linkwarden/linkwarden:v2.3.0

**Comment by craigtrevor** [comment]
`ghcr.io/linkwarden/linkwarden:latest` worked. And now the extension is working. Many thanks for your help.

**Comment by crkos** [comment]
No problem
