### ISSUE TITLE
Please don't hog Ctrl+Shift+V or at least give the option to disable it

### ISSUE THREAD

**Issue by xJayMorex** [linkwarden/browser-extension#66]
Ctrl+Shift+V in Windows is paste data only (without formatting), which is a pretty important keyboard shortcut.

**Comment by crkos** [comment]
is Ctrl+Shift+F ok?

55683ec

**Comment by xJayMorex** [comment]
@crkos I'd vote Ctrl + Shift + D if that is available, because it would be pretty intuitive, given that Ctrl + D bookmarks the current page in Chrome natively.

**Comment by crkos** [comment]
Ok sure

**Comment by xJayMorex** [comment]
I don't want to be the one to decide, but I think if someone is using this great browser extension _instead of_ the native bookmark manager of the browser, they probably wouldn't mind if it would be **Ctrl + D** even. That way, **Ctrl + Shift + D** is free for some future functionality (e.g. open bookmark manager window). Not sure if that would work.

**Comment by gioxx** [comment]
It would be perfect to let the user choose the shortcut but not propose a default one because it might conflict with other existing shortcuts. In browsers the CTRL+Shift+V is for pasting text without formatting and it is essential not to occupy the shortcut with anything else.
Thanks!

**Comment by crkos** [comment]
The default will stay as:
"default": "Ctrl+Shift+F",
"mac": "Command+Shift+F"

If y'all want to change this go to {browser]://extensions/shortcuts

The shortcut is defined at build time, I dont know if it could change at runtime my guess it is, but i dont see the point on doing that since the browser already supports it
