### ISSUE TITLE
[FEAT] When saving bookmark, indicate successful addition to server

### ISSUE THREAD

**Issue by deafmute1** [linkwarden/browser-extension#67]
Currently no indication if tab is saved when hitting save in extension UI - save goes grey upon click but this does not mean bookmark is saved on server.

Unfortunately there is some small delay, and saving the bookmark seems to fail most times if you switch or close the tab.
Therefore you are left stuck there waiting for some unknown amt of time for it to save.

Very unpleasant user experience - my workaround is to count to 3 in my head when saving a page .. not great.

**Comment by crkos** [comment]
There should be an indication on the extension before it closes itself, i will check that

**Comment by crkos** [comment]
It should look like this now
![sucess-extension](https://github.com/linkwarden/browser-extension/assets/92697104/85d207de-5cdd-4c18-8ec3-b53f8b1a17f0)

It had a timeout about 1000ms I had it increased in the last commit to 3500ms.

55683ec
