### ISSUE TITLE
Still requiring a password and username when enabling SSO login.

### ISSUE THREAD

**Issue by harukodi** [linkwarden/browser-extension#74]
When i click the enable SSO button the extension still asks me for a username and a password looks like this!

![image](https://github.com/linkwarden/browser-extension/assets/48220443/bb52bc46-866c-4609-8746-9aec6760bd7f)

As a workaround i just fill in the username and password with a blank space should it be like this?

**Comment by crkos** [comment]
This is intented behaviour, That data is intented as dummy data, so no matter what you put on it, as long as you have a session initiated with the SSO you should be able to use it, This is removed on the latested updates, and instead uses api keys
