### ISSUE TITLE
Error saving pages in firefox extension

### ISSUE THREAD

**Issue by paulhovey** [linkwarden/browser-extension#85]
I started seeing this error in the Firefox extension right after Linkwarden 2.8 was released, so it would seem likely it is related to that update.  Whenever I try to save a link using the extension, a red error box comes up with the text:

```Error: Required [type]```

I've tried different combinations of fields in the extension, but no luck getting it to work.

**Comment by daniel31x13** [comment]
Hello, sorry for the inconvenience.
Is this only happening in Firefox? Or is it in every browser?

**Comment by daniel31x13** [comment]
Okay looks like a bug, will be fixing it in a couple of minutes...

**Comment by daniel31x13** [comment]
The bug is fixed :)

**Comment by paulhovey** [comment]
Awesome, thank you!
